CREATE DATABASE papy;

USE papy;

CREATE TABLE Produit(
	CODART CHAR(4) PRIMARY KEY,
	LIBART VARCHAR(30),
	STIALE INT(10),
	STKPHY INT(10),
	QTEANN INT(10),
	UNIMES CHAR(5)
);

CREATE TABLE Fournis(
	NUMFOU VARCHAR(25) PRIMARY KEY,
	NOMFOU VARCHAR(25),
	RUEFOU VARCHAR(50),
	POSFOU CHAR(5),
	VILFOU VARCHAR(30),
	CONFOU VARCHAR(15),
	SATISF TINYINT CHECK (SATISF BETWEEN 1 AND 10)
);

CREATE TABLE Entcom(
	NUMCOM INT(10) PRIMARY KEY AUTO_INCREMENT,
	OBSCOM VARCHAR(50),
	DATCOM DATE,
	NUMFOU VARCHAR(25) REFERENCES Fournis(NUMFOU)
);

DROP TABLE Ligcom; 

CREATE TABLE Ligcom(
	NUMLIG TINYINT(3),
	QTECDE INT(10),
	PRIUNI VARCHAR(50),
	QTELIV INT(10),
	DERLIV DATETIME,
	NUMCOM INT(10),
	CODART CHAR(4) REFERENCES Produit(CODART),
	PRIMARY KEY (NUMLIG,NUMCOM),
	FOREIGN KEY (NUMCOM) REFERENCES Entcom(NUMCOM)
);

CREATE TABLE Vente(
	DELLIV SMALLINT(5),
	QTE1 INT(10),
	PRIX1 VARCHAR(50),
	QTE2 INT(10),
	PRIX2 VARCHAR(50),
	QTE3 INT(10),
	PRIX3 VARCHAR(50),
	CODART CHAR(4),
	NUMFOU VARCHAR(25),
	PRIMARY KEY (CODART, NUMFOU),
    FOREIGN KEY (CODART) REFERENCES Produit(CODART),
    FOREIGN KEY (NUMFOU) REFERENCES Fournis(NUMFOU)
);

CREATE INDEX ind_tes
ON Entcom(NUMFOU);





